using Cyborg.Modules.Named;
using Cyborg.Modules.Subprocess;

namespace Cyborg.Modules.Tests.Core.AutoInterpolation;

/// <summary>
/// Tests that verify the auto-interpolation infrastructure generated by <c>InterpolationSectionRenderer</c>.
/// The generated <c>__ApplyInterpolation</c> method runs inside <c>ValidateAsync</c> after defaults and overrides
/// have been applied, so every string-typed property on a module and its nested <c>[Validatable]</c> records is
/// resolved against the runtime environment before validation constraints are checked. Workers therefore receive
/// a fully interpolated module and must not call <c>runtime.Environment.Interpolate</c> manually.
/// </summary>
[TestClass]
public sealed class AutoInterpolationTests : ModuleTestBase
{
    private string? _tempExecutable;

    [TestInitialize]
    public void Setup() => _tempExecutable = Path.GetTempFileName();

    [TestCleanup]
    public void Cleanup()
    {
        if (_tempExecutable is not null && File.Exists(_tempExecutable))
        {
            File.Delete(_tempExecutable);
        }
    }

    // -----------------------------------------------------------------------
    // NamedModuleReferenceModule - flat top-level string property
    // -----------------------------------------------------------------------

    [TestMethod]
    public Task Test_FlatStringProperty_ResolvesEnvironmentVariable() =>
        TestOverridesAsync<NamedModuleReferenceModule>(
            """{ "cyborg.modules.named.ref.v1": { "target": "${resolved_target}" } }""",
            env => env.SetVariable("resolved_target", "my-module"),
            module => MSAssert.AreEqual("my-module", module.Target));

    [TestMethod]
    public Task Test_FlatStringProperty_LiteralValuePassesThrough() =>
        TestOverridesAsync<NamedModuleReferenceModule>(
            """{ "cyborg.modules.named.ref.v1": { "target": "literal-module" } }""",
            static _ => { },
            module => MSAssert.AreEqual("literal-module", module.Target));

    [TestMethod]
    public Task Test_FlatStringProperty_MultipleVariablesInSingleString() =>
        TestOverridesAsync<NamedModuleReferenceModule>(
            """{ "cyborg.modules.named.ref.v1": { "target": "${ns}/${name}" } }""",
            env =>
            {
                env.SetVariable("ns", "backup-jobs");
                env.SetVariable("name", "daily");
            },
            module => MSAssert.AreEqual("backup-jobs/daily", module.Target));

    // -----------------------------------------------------------------------
    // SubprocessModule - nested [Validatable] record string property
    // -----------------------------------------------------------------------

    [TestMethod]
    public Task Test_NestedRecordStringProperty_ResolvesEnvironmentVariable()
    {
        const string JSON = """
            {
              "cyborg.modules.subprocess.v1": {
                "command": {
                  "executable": "${my_exec}",
                  "arguments": []
                }
              }
            }
            """;
        return TestOverridesAsync<SubprocessModule>(
            JSON,
            env => env.SetVariable("my_exec", _tempExecutable!),
            module => MSAssert.AreEqual(_tempExecutable, module.Command.Executable));
    }

    // -----------------------------------------------------------------------
    // SubprocessModule - IReadOnlyCollection<string> elements
    // -----------------------------------------------------------------------

    [TestMethod]
    public Task Test_StringCollectionElements_AllElementsResolved()
    {
        const string JSON = """
            {
              "cyborg.modules.subprocess.v1": {
                "command": {
                  "executable": "${my_exec}",
                  "arguments": ["${arg_one}", "literal-arg", "${arg_two}"]
                }
              }
            }
            """;
        return TestOverridesAsync<SubprocessModule>(
            JSON,
            env =>
            {
                env.SetVariable("my_exec", _tempExecutable!);
                env.SetVariable("arg_one", "first");
                env.SetVariable("arg_two", "third");
            },
            module =>
            {
                List<string> args = [.. module.Command.Arguments];
                MSAssert.HasCount(3, args);
                MSAssert.AreEqual("first", args[0]);
                MSAssert.AreEqual("literal-arg", args[1]);
                MSAssert.AreEqual("third", args[2]);
            });
    }

    [TestMethod]
    public Task Test_EmptyStringCollection_RemainsEmpty()
    {
        const string JSON = """
            {
              "cyborg.modules.subprocess.v1": {
                "command": {
                  "executable": "${my_exec}",
                  "arguments": []
                }
              }
            }
            """;
        return TestOverridesAsync<SubprocessModule>(
            JSON,
            env => env.SetVariable("my_exec", _tempExecutable!),
            module => MSAssert.IsEmpty(module.Command.Arguments));
    }

    // -----------------------------------------------------------------------
    // SubprocessModule - nullable string property
    // -----------------------------------------------------------------------

    [TestMethod]
    public Task Test_NullableStringProperty_WhenAbsent_RemainsNull()
    {
        const string JSON = """
            {
              "cyborg.modules.subprocess.v1": {
                "command": {
                  "executable": "${my_exec}",
                  "arguments": []
                }
              }
            }
            """;
        return TestOverridesAsync<SubprocessModule>(
            JSON,
            env => env.SetVariable("my_exec", _tempExecutable!),
            module => MSAssert.IsNull(module.Command.WorkingDirectory));
    }

    // -----------------------------------------------------------------------
    // SubprocessModule - IReadOnlyCollection<EnvironmentVariable> (collection of [Validatable] records)
    // -----------------------------------------------------------------------

    [TestMethod]
    public Task Test_CollectionOfValidatableRecords_StringPropertiesResolved()
    {
        const string JSON = """
            {
              "cyborg.modules.subprocess.v1": {
                "command": {
                  "executable": "${my_exec}",
                  "arguments": []
                },
                "environment_variables": [
                  { "key": "${env_key}", "value": "${env_val}" }
                ]
              }
            }
            """;
        return TestOverridesAsync<SubprocessModule>(
            JSON,
            env =>
            {
                env.SetVariable("my_exec", _tempExecutable!);
                env.SetVariable("env_key", "MY_KEY");
                env.SetVariable("env_val", "my-value");
            },
            module =>
            {
                MSAssert.IsNotNull(module.EnvironmentVariables);
                MSAssert.HasCount(1, module.EnvironmentVariables);
                EnvironmentVariable entry = module.EnvironmentVariables.First();
                MSAssert.AreEqual("MY_KEY", entry.Key);
                MSAssert.AreEqual("my-value", entry.Value);
            });
    }

    [TestMethod]
    public Task Test_CollectionOfValidatableRecords_MultipleElementsEachResolved()
    {
        const string JSON = """
            {
              "cyborg.modules.subprocess.v1": {
                "command": {
                  "executable": "${my_exec}",
                  "arguments": []
                },
                "environment_variables": [
                  { "key": "${k1}", "value": "${v1}" },
                  { "key": "${k2}", "value": "${v2}" }
                ]
              }
            }
            """;
        return TestOverridesAsync<SubprocessModule>(
            JSON,
            env =>
            {
                env.SetVariable("my_exec", _tempExecutable!);
                env.SetVariable("k1", "KEY_ONE");
                env.SetVariable("v1", "val-one");
                env.SetVariable("k2", "KEY_TWO");
                env.SetVariable("v2", "val-two");
            },
            module =>
            {
                MSAssert.IsNotNull(module.EnvironmentVariables);
                List<EnvironmentVariable> envVars = [.. module.EnvironmentVariables];
                MSAssert.HasCount(2, envVars);
                MSAssert.AreEqual("KEY_ONE", envVars[0].Key);
                MSAssert.AreEqual("val-one", envVars[0].Value);
                MSAssert.AreEqual("KEY_TWO", envVars[1].Key);
                MSAssert.AreEqual("val-two", envVars[1].Value);
            });
    }

    [TestMethod]
    public Task Test_NullOptionalCollection_RemainsNull()
    {
        const string JSON = """
            {
              "cyborg.modules.subprocess.v1": {
                "command": {
                  "executable": "${my_exec}",
                  "arguments": []
                }
              }
            }
            """;
        return TestOverridesAsync<SubprocessModule>(
            JSON,
            env => env.SetVariable("my_exec", _tempExecutable!),
            module => MSAssert.IsNull(module.EnvironmentVariables));
    }

    // -----------------------------------------------------------------------
    // SubprocessModule - optional nullable nested [Validatable] record
    // -----------------------------------------------------------------------

    [TestMethod]
    public Task Test_OptionalNestedRecord_WhenAbsent_RemainsNull()
    {
        const string JSON = """
            {
              "cyborg.modules.subprocess.v1": {
                "command": {
                  "executable": "${my_exec}",
                  "arguments": []
                }
              }
            }
            """;
        return TestOverridesAsync<SubprocessModule>(
            JSON,
            env => env.SetVariable("my_exec", _tempExecutable!),
            module => MSAssert.IsNull(module.Impersonation));
    }

    [TestMethod]
    public async Task Test_OptionalNestedRecord_WhenPresent_StringPropertiesResolved()
    {
        string tempImpersonationExec = Path.GetTempFileName();
        try
        {
            const string JSON = """
                {
                  "cyborg.modules.subprocess.v1": {
                    "command": {
                      "executable": "${my_exec}",
                      "arguments": []
                    },
                    "impersonation": {
                      "executable": "${imp_exec}",
                      "user": "${imp_user}"
                    }
                  }
                }
                """;
            await TestOverridesAsync<SubprocessModule>(
                JSON,
                env =>
                {
                    env.SetVariable("my_exec", _tempExecutable!);
                    env.SetVariable("imp_exec", tempImpersonationExec);
                    env.SetVariable("imp_user", "backup-user");
                },
                module =>
                {
                    MSAssert.IsNotNull(module.Impersonation);
                    MSAssert.AreEqual(tempImpersonationExec, module.Impersonation.Executable);
                    MSAssert.AreEqual("backup-user", module.Impersonation.User);
                });
        }
        finally
        {
            if (File.Exists(tempImpersonationExec))
            {
                File.Delete(tempImpersonationExec);
            }
        }
    }
}
